---
- name: Install required packages
  dnf:
    name: "{{ item }}"
    state: present
    update_cache: True
  loop: 
    - bash
    - curl
    - grep

- name: Install required packages
  dnf:
    name: "{{ item }}"
    state: present
    update_cache: True
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux', 'Rocky']
  loop:
    - iscsi-initiator-utils
